management:
  endpoints:
    web:
      exposure:
        include:
          - env

spring:
  datasource:
    url: jdbc:postgresql://pg-5bdffa4-candidate-tracker.a.aivencloud.com:22880/defaultdb?sslmode=require
    username: avnadmin
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  openingsEmailEnabled: true

  mail:
    host: smtp.gmail.com
    username: no-reply@i-raysolutions.com
    password: ${MAIL_PASSWORD}
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  servlet:
    multipart:
      maxFileSize: 100MB
      max-request-size: 100MB

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8098

actuator:
  username: admin
  secret: secret@2020