management.endpoints.web.exposure.include=metrics,prometheus,health
spring.config.import=optional:aws-secretsmanager:test/secretmanager
logging.level.io.awspring.cloud.secretsmanager= debug

#Swagger3 OpenAPI properties
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=subhashtadi8883@gmail.com
spring.mail.password=ykkt xnvz gluq pijd
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true