management:
  endpoints:
    web:
      exposure:
        include:
          - env

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/RESOURCES
    username: postgres
    password: Dev@12345!
    driver-class-name: org.postgresql.Driver

  openingsEmailEnabled: true

  mail:
    host: smtp.gmail.com
    username: jeevanteja000@gmail.com
    password: uhsagoqmwzqyxlnn
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  servlet:
    multipart:
      maxFileSize: 100MB
      max-request-size: 100MB

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8098

actuator:
  username: admin
  secret: secret@2020