management.endpoints.web.exposure.include=metrics,prometheus,health
#spring.config.import=optional:aws-secretsmanager:test/secretmanager
#logging.level.io.awspring.cloud.secretsmanager= debug

#Swagger3 OpenAPI properties
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

spring.datasource.url=jdbc:postgresql://pg-5bdffa4-candidate-tracker.a.aivencloud.com:22880/defaultdb?sslmode=require
spring.datasource.username=avnadmin
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.hikari.maximum-pool-size=10